name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn rebuild
      - run: yarn artifact:generate
      - run: yarn --immutable --immutable-cache --check-cache --inline-builds
      - run: yarn test
